[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
description = ""

[tool.poetry.dependencies]
pandas = "*"
python = "^3.7"
scipy = "*"
matplotlib = "^3.6.0"
numpy = "^1.23.3"
